PLAYFIELD_WIDTH = 80
PLAYFIELD_HEIGHT = 40

MESSAGE_ROW = 0
PLAYFIELD_TOP = 1
STATUS_ROW = PLAYFIELD_TOP + PLAYFIELD_HEIGHT

MIN_TERMINAL_WIDTH = PLAYFIELD_WIDTH
MIN_TERMINAL_HEIGHT = PLAYFIELD_HEIGHT + 2
