PLAYFIELD_WIDTH = 160
PLAYFIELD_HEIGHT = 40
WORLD_WIDTH = PLAYFIELD_WIDTH * 2
WORLD_HEIGHT = PLAYFIELD_HEIGHT * 2

MESSAGE_ROW = 0
PLAYFIELD_TOP = 1
STATUS_ROW = PLAYFIELD_TOP + PLAYFIELD_HEIGHT

MIN_TERMINAL_WIDTH = PLAYFIELD_WIDTH
MIN_TERMINAL_HEIGHT = PLAYFIELD_HEIGHT + 2
